style: remove redundant codes
sparcs-kaist/sparcs_home pull request #17
Opened 2018-02-20 00:45 UTC by gunwooterry

테스트 필요합니다.

2018-02-20 12:53 UTC, luaneyed requested changes

2018-02-20 12:53 UTC, sangguk2 commented on src/components/Projects.vue
> +  import * as projects from '../text/projects';
이거 없어서 에러나요

2018-02-20 14:53 UTC, gunwooterry commented on src/components/Projects.vue
> +  import * as projects from '../text/projects';
저 파일이 없다는 말임? 나 로컬에서 세팅이 안 돼서 테스트를 못한다ㅠ

2018-02-20 15:09 UTC, sangguk2 commented on src/components/Projects.vue
> +  import * as projects from '../text/projects';
ㅇㅇ 저 파일이 걍 없음 ㅋㅋㅋㅋㅋ
너 맥북있지않아??

2018-02-21 00:38 UTC, gunwooterry commented on src/components/Projects.vue
> +  import * as projects from '../text/projects';
맥북은 있는데 MongoDB 에러 발생해서 세팅이 안 되더라고ㅠ 일단 빠진 거 추가해서 넣어봤음

2021-12-08 00:33 UTC, closed without merging